include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/generated/**
    - lib/routes/app_router.gr.dart
    

linter:
  rules:
    avoid_void_async: true
    omit_local_variable_types: false
    prefer_single_quotes: false
    avoid_unnecessary_containers: true
    prefer_relative_imports: true
  